copy ..\..\..\Build\Debug\CjClutter.ObjLoader.Loader.dll 		References\CjClutter.ObjLoader.Loader.dll
copy ..\..\..\Build\Debug\CjClutter.ObjLoader.Loader.pdb 		References\CjClutter.ObjLoader.Loader.pdb
copy ..\..\..\Build\Debug\Clarity.Common.dll 					References\Clarity.Common.dll
copy ..\..\..\Build\Debug\Clarity.Common.pdb 					References\Clarity.Common.pdb
copy ..\..\..\Build\Debug\Clarity.Core.dll 						References\Clarity.Core.dll
copy ..\..\..\Build\Debug\Clarity.Core.pdb 						References\Clarity.Core.pdb
copy ..\..\..\Build\Debug\Clarity.Engine.dll 					References\Clarity.Engine.dll
copy ..\..\..\Build\Debug\Clarity.Engine.pdb 					References\Clarity.Engine.pdb
copy ..\..\..\Build\Debug\Clarity.Ext.StoryLayout.Building.dll 	References\Clarity.Ext.StoryLayout.Building.dll
copy ..\..\..\Build\Debug\Clarity.Ext.StoryLayout.Building.pdb 	References\Clarity.Ext.StoryLayout.Building.pdb
copy ..\..\..\Build\Debug\PtrMagic.dll 							References\PtrMagic.dll
copy ..\..\..\Build\Debug\JitsuGen.Core.dll 					References\JitsuGen.Core.dll
copy ..\..\..\Build\Debug\JitsuGen.Core.pdb 					References\JitsuGen.Core.pdb
copy ..\..\..\Build\Debug\JitsuGen.Output.dll 					References\JitsuGen.Output.dll
copy ..\..\..\Build\Debug\JitsuGen.Output.pdb 					References\JitsuGen.Output.pdb
copy ..\..\..\Build\Debug\Newtonsoft.Json.dll 					References\Newtonsoft.Json.dll
