//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean ResetPlayer
        {
            get
            {
                return SteamVR_Actions.default_ResetPlayer;
            }
        }
        
        public virtual SteamVR_Action_Boolean NavigateNext
        {
            get
            {
                return SteamVR_Actions.default_NavigateNext;
            }
        }
        
        public virtual SteamVR_Action_Boolean NavigatePrev
        {
            get
            {
                return SteamVR_Actions.default_NavigatePrev;
            }
        }
        
        public virtual SteamVR_Action_Boolean ChangeMode
        {
            get
            {
                return SteamVR_Actions.default_ChangeMode;
            }
        }
        
        public virtual SteamVR_Action_Vector2 DpadOrientation
        {
            get
            {
                return SteamVR_Actions.default_DpadOrientation;
            }
        }
        
        public virtual SteamVR_Action_Boolean ElevatorUp
        {
            get
            {
                return SteamVR_Actions.default_ElevatorUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean ElevatorDown
        {
            get
            {
                return SteamVR_Actions.default_ElevatorDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean RotateLeft
        {
            get
            {
                return SteamVR_Actions.default_RotateLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean RotateRight
        {
            get
            {
                return SteamVR_Actions.default_RotateRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean MinimapToggle
        {
            get
            {
                return SteamVR_Actions.default_MinimapToggle;
            }
        }
        
        public virtual SteamVR_Action_Boolean MinimapZoomModifier
        {
            get
            {
                return SteamVR_Actions.default_MinimapZoomModifier;
            }
        }
        
        public virtual SteamVR_Action_Pose LaserPose
        {
            get
            {
                return SteamVR_Actions.default_LaserPose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
