namespace IritNet
{
    public enum BoolFatalErrorType
    {
        BOOL_ERR_NO_POLY_OBJ,
        BOOL_ERR_NO_BOOL_OP_SUPPORT,
        BOOL_ERR_NO_MATCH_POINT,
        BOOL_ERR_NO_ELMNT_TO_DEL,
        BOOL_ERR_SORT_INTER_LIST,
        BOOL_ERR_FIND_VERTEX_FAILED,
        BOOL_ERR_NO_COPLANAR_VRTX,
        BOOL_ERR_NO_OPEN_LOOP,
        BOOL_ERR_NO_NEWER_VERTEX,
        BOOL_ERR_NO_INTERSECTION,
        BOOL_ERR_LOOP_LESS_3_VRTCS,
        BOOL_ERR_NO_INVERSE_MAT,
        BOOL_ERR_ADJ_STACK_OF,
        BOOL_ERR_CIRC_VRTX_LST,
        BOOL_ERR_NO_2D_OP_SUPPORT,
        BOOL_ERR_NO_PLLN_MATCH,
        BOOL_ERR_DISJ_PROP_ERR,
        BOOL_ERR_EMPTY_POLY_OBJ,

        BOOL_ERR_UNDEFINE_ERR
    }
}