namespace IritNet
{
    public enum CagdPointType
    {       /* Type of control point. The P-types are rationals. */
        CAGD_PT_NONE = 0,
        CAGD_PT_BASE = 1100,              /* Must be an even number. */
        CAGD_PT_E1_TYPE = 1100,
        CAGD_PT_P1_TYPE,
        CAGD_PT_E2_TYPE,
        CAGD_PT_P2_TYPE,
        CAGD_PT_E3_TYPE,
        CAGD_PT_P3_TYPE,
        CAGD_PT_E4_TYPE,
        CAGD_PT_P4_TYPE,
        CAGD_PT_E5_TYPE,
        CAGD_PT_P5_TYPE,
        CAGD_PT_E6_TYPE,
        CAGD_PT_P6_TYPE,
        CAGD_PT_E7_TYPE,
        CAGD_PT_P7_TYPE,
        CAGD_PT_E8_TYPE,
        CAGD_PT_P8_TYPE,
        CAGD_PT_E9_TYPE,
        CAGD_PT_P9_TYPE,
        CAGD_PT_E10_TYPE,
        CAGD_PT_P10_TYPE,
        CAGD_PT_E11_TYPE,
        CAGD_PT_P11_TYPE,
        CAGD_PT_E12_TYPE,
        CAGD_PT_P12_TYPE,
        CAGD_PT_E13_TYPE,
        CAGD_PT_P13_TYPE,
        CAGD_PT_E14_TYPE,
        CAGD_PT_P14_TYPE,
        CAGD_PT_E15_TYPE,
        CAGD_PT_P15_TYPE,
        CAGD_PT_E16_TYPE,
        CAGD_PT_P16_TYPE,
        CAGD_PT_E17_TYPE,
        CAGD_PT_P17_TYPE,
        CAGD_PT_E18_TYPE,
        CAGD_PT_P18_TYPE,
        CAGD_PT_MAX_SIZE_TYPE        /* See also CAGD_MAX_* constants below. */
    }
}