namespace IritNet
{
    public enum MvarPointType
    {
        MVAR_PT_NONE = CagdPointType.CAGD_PT_NONE,
        MVAR_PT_BASE = CagdPointType.CAGD_PT_BASE,                  /* Must be an even number. */
        MVAR_PT_E1_TYPE = CagdPointType.CAGD_PT_E1_TYPE,
        MVAR_PT_P1_TYPE,
        MVAR_PT_E2_TYPE,
        MVAR_PT_P2_TYPE,
        MVAR_PT_E3_TYPE,
        MVAR_PT_P3_TYPE,
        MVAR_PT_E4_TYPE,
        MVAR_PT_P4_TYPE,
        MVAR_PT_E5_TYPE,
        MVAR_PT_P5_TYPE,
        MVAR_PT_E6_TYPE,
        MVAR_PT_P6_TYPE,
        MVAR_PT_E7_TYPE,
        MVAR_PT_P7_TYPE,
        MVAR_PT_E8_TYPE,
        MVAR_PT_P8_TYPE,
        MVAR_PT_E9_TYPE,
        MVAR_PT_P9_TYPE,
        MVAR_PT_E10_TYPE,
        MVAR_PT_P10_TYPE,
        MVAR_PT_E11_TYPE,
        MVAR_PT_P11_TYPE,
        MVAR_PT_E12_TYPE,
        MVAR_PT_P12_TYPE,
        MVAR_PT_E13_TYPE,
        MVAR_PT_P13_TYPE,
        MVAR_PT_E14_TYPE,
        MVAR_PT_P14_TYPE,
        MVAR_PT_E15_TYPE,
        MVAR_PT_P15_TYPE,
        MVAR_PT_E16_TYPE,
        MVAR_PT_P16_TYPE,
        MVAR_PT_E17_TYPE,
        MVAR_PT_P17_TYPE,
        MVAR_PT_E18_TYPE,
        MVAR_PT_P18_TYPE,
        MVAR_PT_E19_TYPE,
        MVAR_PT_P19_TYPE,
        MVAR_PT_MAX_SIZE_TYPE	     /* See also MVAR_MAX_* constants below. */
    }
}