namespace IritNet
{
    public enum TrivIGAErrorType
    {
        TRIV_IGA_ERR_NO_ERROR,
        TRIV_IGA_ERR_INVALID_ARRANGMENT,
        TRIV_IGA_ERR_INVALID_INPUT,
        TRIV_IGA_ERR_RATIONAL_NO_SUPPORT,
        TRIV_IGA_ERR_BEZIER_NO_SUPPORT,
        TRIV_IGA_ERR_INVALID_PATCH_INDEX,
        TRIV_IGA_ERR_INVALID_DIR,
        TRIV_IGA_ERR_ID_NOT_FOUND,
        TRIV_IGA_ERR_INVALID_EVAL_TYPE,
        TRIV_IGA_ERR_NOT_BNDRY_PARAMS,
        TRIV_IGA_ERR_NOT_ZERO_ONE_PARAM,
        TRIV_IGA_ERR_EXISTING_MATERIAL_ADDED,
        TRIV_IGA_ERR_INVALID_FIELD_ATTRIBUTES_FORMAT,
        TRIV_IGA_ERR_UNDEFINED_FIELD_MATERIAL,
        TRIV_IGA_ERR_INCOMPATIBLE_PT_TYPE,
        TRIV_IGA_ERR_SRFS_NOT_COMPATIBLE,
        TRIV_IGA_ERR_ID_OUT_OF_RANGE,
        TRIV_IGA_ERR_SRFS_NOT_SUBSPACES,
        TRIV_IGA_ERR_UNDEFINE_ERR
    }
}