namespace IritNet
{
    public enum User3DSpreadType
    {
        USER_3D_SPREAD_RANDOM,
        USER_3D_SPREAD_DIAG_PLANE,
        USER_3D_SPREAD_DIAG_PLANE2,
        USER_3D_SPREAD_ANTI_DIAG_PLANE,
        USER_3D_SPREAD_ANTI_DIAG_PLANE2,
        USER_3D_SPREAD_ANTI_DIAG_PLANE3,
        USER_3D_SPREAD_DISCONT2PLANE,
        USER_3D_SPREAD_DISCONT4PLANE,
    }
}