namespace IritNet
{
    public enum UserKnmtcsConstrType
    {
        USER_KNMTCS_CONSTR_NONE = 0,
        USER_KNMTCS_CONSTR_DIST_PT_PT,
        USER_KNMTCS_CONSTR_DIST_PT_BAR,
        USER_KNMTCS_CONSTR_DIST_PT_CRV,
        USER_KNMTCS_CONSTR_DIST_PT_SRF,
        USER_KNMTCS_CONSTR_DIST_BAR_BAR,
        USER_KNMTCS_CONSTR_DIST_BAR_CRV,
        USER_KNMTCS_CONSTR_DIST_BAR_SRF,
        USER_KNMTCS_CONSTR_ANGLE,
        USER_KNMTCS_CONSTR_ORTHOGONALITY,
        USER_KNMTCS_CONSTR_TANGENCY,
        USER_KNMTCS_CONSTR_PARALLEL,
        USER_KNMTCS_CONSTR_ROT_CRV,

        USER_KNMTCS_CONSTR_MIN_DIST_PT_PT,/* In equality constraints from here. */
        USER_KNMTCS_CONSTR_MAX_DIST_PT_PT,
        USER_KNMTCS_CONSTR_XDIFF_POS,
        USER_KNMTCS_CONSTR_YDIFF_POS,
        USER_KNMTCS_CONSTR_ZDIFF_POS
    }
}